/*
 * Created on 14 Apr 2015 ( Time 18:45:46 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.stories.business.service.mapping;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.stories.bean.Usertable;
import org.stories.bean.jpa.UsertableEntity;
import org.stories.test.MockValues;

/**
 * Test : Mapping between entity beans and display beans.
 */
public class UsertableServiceMapperTest {

	private UsertableServiceMapper usertableServiceMapper;

	private static ModelMapper modelMapper = new ModelMapper();

	private MockValues mockValues = new MockValues();
	
	
	@BeforeClass
	public static void setUp() {
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}
	
	@Before
	public void before() {
		usertableServiceMapper = new UsertableServiceMapper();
		usertableServiceMapper.setModelMapper(modelMapper);
	}
	
	/**
	 * Mapping from 'UsertableEntity' to 'Usertable'
	 * @param usertableEntity
	 */
	@Test
	public void testMapUsertableEntityToUsertable() {
		// Given
		UsertableEntity usertableEntity = new UsertableEntity();
		usertableEntity.setDelay(mockValues.nextInteger());
		usertableEntity.setCreated(mockValues.nextInteger());
		usertableEntity.setKarma(mockValues.nextInteger());
		
		// When
		Usertable usertable = usertableServiceMapper.mapUsertableEntityToUsertable(usertableEntity);
		
		// Then
		assertEquals(usertableEntity.getDelay(), usertable.getDelay());
		assertEquals(usertableEntity.getCreated(), usertable.getCreated());
		assertEquals(usertableEntity.getKarma(), usertable.getKarma());
	}
	
	/**
	 * Test : Mapping from 'Usertable' to 'UsertableEntity'
	 */
	@Test
	public void testMapUsertableToUsertableEntity() {
		// Given
		Usertable usertable = new Usertable();
		usertable.setDelay(mockValues.nextInteger());
		usertable.setCreated(mockValues.nextInteger());
		usertable.setKarma(mockValues.nextInteger());

		UsertableEntity usertableEntity = new UsertableEntity();
		
		// When
		usertableServiceMapper.mapUsertableToUsertableEntity(usertable, usertableEntity);
		
		// Then
		assertEquals(usertable.getDelay(), usertableEntity.getDelay());
		assertEquals(usertable.getCreated(), usertableEntity.getCreated());
		assertEquals(usertable.getKarma(), usertableEntity.getKarma());
	}

}