/*
 * Created on 14 Apr 2015 ( Time 18:41:17 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.stories.web.listitem;

import org.stories.bean.Comment;
import org.stories.web.common.ListItem;

public class CommentListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public CommentListItem(Comment comment) {
		super();

		this.value = ""
			 + comment.getId()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = comment.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
