/*
 * Created on 14 Apr 2015 ( Time 18:41:17 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.stories.web.listitem;

import org.stories.bean.Usertable;
import org.stories.web.common.ListItem;

public class UsertableListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public UsertableListItem(Usertable usertable) {
		super();

		this.value = ""
			 + usertable.getId()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = usertable.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
