/*
 * Created on 14 Apr 2015 ( Time 18:41:17 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.stories.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class Comment implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Size( max = 20 )
    private String by;


    private Integer parent;

    @Size( max = 50 )
    private String text;


    private Date time;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setBy( String by ) {
        this.by = by;
    }
    public String getBy() {
        return this.by;
    }

    public void setParent( Integer parent ) {
        this.parent = parent;
    }
    public Integer getParent() {
        return this.parent;
    }

    public void setText( String text ) {
        this.text = text;
    }
    public String getText() {
        return this.text;
    }

    public void setTime( Date time ) {
        this.time = time;
    }
    public Date getTime() {
        return this.time;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(by);
        sb.append("|");
        sb.append(parent);
        sb.append("|");
        sb.append(text);
        sb.append("|");
        sb.append(time);
        return sb.toString(); 
    } 


}
