/*
 * Created on 14 Apr 2015 ( Time 18:41:17 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.stories.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class Submission implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Size( max = 20 )
    private String by;


    private Integer descendants;


    private Integer scores;


    private Date time;

    @Size( max = 20 )
    private String title;

    @Size( max = 20 )
    private String type;

    @Size( max = 20 )
    private String url;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setBy( String by ) {
        this.by = by;
    }
    public String getBy() {
        return this.by;
    }

    public void setDescendants( Integer descendants ) {
        this.descendants = descendants;
    }
    public Integer getDescendants() {
        return this.descendants;
    }

    public void setScores( Integer scores ) {
        this.scores = scores;
    }
    public Integer getScores() {
        return this.scores;
    }

    public void setTime( Date time ) {
        this.time = time;
    }
    public Date getTime() {
        return this.time;
    }

    public void setTitle( String title ) {
        this.title = title;
    }
    public String getTitle() {
        return this.title;
    }

    public void setType( String type ) {
        this.type = type;
    }
    public String getType() {
        return this.type;
    }

    public void setUrl( String url ) {
        this.url = url;
    }
    public String getUrl() {
        return this.url;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(by);
        sb.append("|");
        sb.append(descendants);
        sb.append("|");
        sb.append(scores);
        sb.append("|");
        sb.append(time);
        sb.append("|");
        sb.append(title);
        sb.append("|");
        sb.append(type);
        sb.append("|");
        sb.append(url);
        return sb.toString(); 
    } 


}
