/*
 * Created on 14 Apr 2015 ( Time 18:41:17 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.stories.bean;

import java.io.Serializable;

import javax.validation.constraints.*;


public class Usertable implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    @Size( min = 1, max = 20 )
    private String id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    

    private Integer delay;


    private Integer created;


    private Integer karma;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( String id ) {
        this.id = id ;
    }

    public String getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setDelay( Integer delay ) {
        this.delay = delay;
    }
    public Integer getDelay() {
        return this.delay;
    }

    public void setCreated( Integer created ) {
        this.created = created;
    }
    public Integer getCreated() {
        return this.created;
    }

    public void setKarma( Integer karma ) {
        this.karma = karma;
    }
    public Integer getKarma() {
        return this.karma;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(delay);
        sb.append("|");
        sb.append(created);
        sb.append("|");
        sb.append(karma);
        return sb.toString(); 
    } 


}
