/*
 * Created on 14 Apr 2015 ( Time 18:41:18 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.stories.web.common;

public enum MessageType {
	
	SUCCESS,
	INFO,
	WARNING,
	DANGER;
	
	public String getCss() {
		return name().toLowerCase();
	}
	
}
