/*
 * Created on 14 Apr 2015 ( Time 18:45:46 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.stories.business.service;

import java.util.List;

import org.stories.bean.Submission;

/**
 * Business Service Interface for entity Submission.
 */
public interface SubmissionService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Submission findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Submission> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Submission save(Submission entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Submission update(Submission entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Submission create(Submission entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );


}
