/*
 * Created on 14 Apr 2015 ( Time 18:45:46 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.stories.business.service;

import java.util.List;

import org.stories.bean.Usertable;

/**
 * Business Service Interface for entity Usertable.
 */
public interface UsertableService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Usertable findById( String id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Usertable> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Usertable save(Usertable entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Usertable update(Usertable entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Usertable create(Usertable entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( String id );


}
