/*
 * Created on 14 Apr 2015 ( Time 18:45:46 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.stories.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.stories.bean.Submission;
import org.stories.bean.jpa.SubmissionEntity;
import org.stories.bean.jpa.UsertableEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class SubmissionServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public SubmissionServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'SubmissionEntity' to 'Submission'
	 * @param submissionEntity
	 */
	public Submission mapSubmissionEntityToSubmission(SubmissionEntity submissionEntity) {
		if(submissionEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Submission submission = map(submissionEntity, Submission.class);

		//--- Link mapping ( link to Usertable )
		if(submissionEntity.getUsertable() != null) {
			submission.setBy(submissionEntity.getUsertable().getId());
		}
		return submission;
	}
	
	/**
	 * Mapping from 'Submission' to 'SubmissionEntity'
	 * @param submission
	 * @param submissionEntity
	 */
	public void mapSubmissionToSubmissionEntity(Submission submission, SubmissionEntity submissionEntity) {
		if(submission == null) {
			return;
		}

		//--- Generic mapping 
		map(submission, submissionEntity);

		//--- Link mapping ( link : submission )
		if( hasLinkToUsertable(submission) ) {
			UsertableEntity usertable1 = new UsertableEntity();
			usertable1.setId( submission.getBy() );
			submissionEntity.setUsertable( usertable1 );
		} else {
			submissionEntity.setUsertable( null );
		}

	}
	
	/**
	 * Verify that Usertable id is valid.
	 * @param Usertable Usertable
	 * @return boolean
	 */
	private boolean hasLinkToUsertable(Submission submission) {
		if(submission.getBy() != null) {
			return true;
		}
		return false;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}