/*
 * Created on 14 Apr 2015 ( Time 18:45:46 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.stories.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.stories.bean.Usertable;
import org.stories.bean.jpa.UsertableEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class UsertableServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public UsertableServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'UsertableEntity' to 'Usertable'
	 * @param usertableEntity
	 */
	public Usertable mapUsertableEntityToUsertable(UsertableEntity usertableEntity) {
		if(usertableEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Usertable usertable = map(usertableEntity, Usertable.class);

		return usertable;
	}
	
	/**
	 * Mapping from 'Usertable' to 'UsertableEntity'
	 * @param usertable
	 * @param usertableEntity
	 */
	public void mapUsertableToUsertableEntity(Usertable usertable, UsertableEntity usertableEntity) {
		if(usertable == null) {
			return;
		}

		//--- Generic mapping 
		map(usertable, usertableEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}